INSERT INTO metadata_utilities.ingestion_column_details (column_name,datatype,ordinal_position,mapping_column, project_id,database_schema,table_name,modified_by,modified_date,created_by,created_date) VALUES 
('TEST_ENTRY_VARCHAR','VARCHAR(50)',1,'TEST_ENTRY_VARCHAR','TEST','TEST','TEST_TABLE','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TEST_ENTRY_BOOLEAN','BOOLEAN',2,'TEST_ENTRY_BOOLEAN','TEST','TEST','TEST_TABLE','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TEST_ENTRY_TIMESTAMP','TIMESTAMP',3,'TEST_ENTRY_TIMESTAMP','TEST','TEST','TEST_TABLE','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TEST_ENTRY_BIGINT','BIGINT',4,'TEST_ENTRY_TIMESTAMP','TEST','TEST','TEST_TABLE','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP);