INSERT INTO metadata_utilities.ingestion_config
(
ingestion_type, --TEST,
source_schema_table_name, --PREFIX_PATH_FILE_NAME, 
primary_key_column, --NULL, 
incremental_date_column, --NULL,
load_type, --FULL,  
extra_parameters, --NULL, 
partitioned_by, --NULL,
api_source_name, --TEST,    
source_system, --GCS,
connection_name, --TEST,
project_id, --TEST
database_schema, --TEST, 
table_name, --TEST_TABLE,
file_format, --CSV, 
header, --NULL,
delimiter, --',',
quote_characters, --'"',
escape_characters, --NULL,
accepted_encoding, --gzip,
is_parquet, --false,
to_parquet, --true,
bucket, --dev-test-data,
bucket_destination, --input/,
archive_destination, --archive/test/,
created_by, --'ADMIN', 
created_date, --CURRENT_TIMESTAMP,
modified_by, --'ADMIN', 
modified_date --CURRENT_TIMESTAMP
)
VALUES
(
'TEST - INGESTION TYPE',
'TEST - PREFIX-FILE-PATH', 
NULL, 
NULL,
'FULL',  
NULL, 
NULL,
'TEST - SOURCE - API',    
'TEST - SOURCE SYSTEM',
'TEST'
'TEST',
'TEST', 
'TEST_TABLE',
'CSV', 
NULL,
',',
'"',
NULL,
'gzip',
false,
true,
'dev-test-data',
'input/',
'archive/test/',
'ADMIN', 
CURRENT_TIMESTAMP,
'ADMIN', 
CURRENT_TIMESTAMP);