DELETE FROM metadata_utilities.ingestion_config WHERE table_name = 'CURRENCY_EXCHANGE_RATES';
INSERT INTO metadata_utilities.ingestion_config
(
ingestion_type, --TEST,
source_schema_table_name, --PREFIX_PATH_FILE_NAME, 
primary_key_column, --NULL, 
incremental_date_column, --NULL,
load_type, --FULL,  
extra_parameters, --NULL, 
partitioned_by, --NULL,
api_source_name, --TEST,    
source_system, --GCS,
connection_name, --TEST,
project_id, --TEST,
database_schema, --TEST, 
table_name, --TEST_TABLE,
file_format, --CSV, 
header, --NULL,
delimiter, --',',
quote_characters, --'"',
escape_characters, --NULL,
accepted_encoding, --gzip,
is_parquet, --false,
to_parquet, --true,
bucket, --dev-test-data,
bucket_destination, --input/,
archive_destination, --archive/test/,
created_by, --'ADMIN', 
created_date, --CURRENT_TIMESTAMP,
modified_by, --'ADMIN', 
modified_date --CURRENT_TIMESTAMP
)
VALUES
(
'REQUEST',
'latest/USD',
null,
'TIME_LAST_UPDATE_UNIX',
'INCR',
null,
null,
'EXCHANGERATE-API 6.0',
'EXCHANGE RATE API',
'EXCHANGERATE',
'COINCAP-DATA-HUB',
'COINCAP_DATA',
'CURRENCY_EXCHANGE_RATES',
'PARQUET',
null,
null,
null,
null,
'gzip',
true,
true,
'dev-coincap-data',
'input/exchangerates/usd/',
'archive/exchangerates/usd/',
'ADMIN',
CURRENT_TIMESTAMP,
'ADMIN',
CURRENT_TIMESTAMP
);

DELETE FROM metadata_utilities.ingestion_column_details WHERE table_name = 'CURRENCY_EXCHANGE_RATES';
INSERT INTO metadata_utilities.ingestion_column_details (column_name,datatype,ordinal_position,mapping_column, project_id, database_schema,table_name,modified_by,modified_date,created_by,created_date) VALUES 
('DOCUMENTATION','STRING',1,'DOCUMENTATION','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TERMS_OF_USE','STRING',2,'TERMS_OF_USE','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TIME_LAST_UPDATE_UNIX','INT64',3,'TIME_LAST_UPDATE_UNIX','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TIME_LAST_UPDATE_UTC','INT64',4,'TIME_LAST_UPDATE_UTC','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TIME_NEXT_UPDATE_UNIX','INT64',5,'TIME_NEXT_UPDATE_UNIX','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('TIME_NEXT_UPDATE_UTC','INT64',6,'TIME_LAST_UPDATE_UTC','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('BASE_CODE','STRING',7,'BASE_CODE','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('CONVERSION_RATES','STRING',8,'CONVERSION_RATES','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('RESULT','STRING',9,'RESULT','COINCAP-DATA-HUB', 'COINCAP_DATA','CURRENCY_EXCHANGE_RATES','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP);