DELETE FROM metadata_utilities.ingestion_config WHERE table_name = 'ASSETS';
INSERT INTO metadata_utilities.ingestion_config
(
ingestion_type, --TEST,
source_schema_table_name, --PREFIX_PATH_FILE_NAME, 
primary_key_column, --NULL, 
incremental_date_column, --NULL,
load_type, --FULL,  
extra_parameters, --NULL, 
partitioned_by, --NULL,
api_source_name, --TEST,    
source_system, --GCS,
connection_name, --TEST,
project_id, --TEST,
database_schema, --TEST, 
table_name, --TEST_TABLE,
file_format, --CSV, 
header, --NULL,
delimiter, --',',
quote_characters, --'"',
escape_characters, --NULL,
accepted_encoding, --gzip,
is_parquet, --false,
to_parquet, --true,
bucket, --dev-test-data,
bucket_destination, --input/,
archive_destination, --archive/test/,
created_by, --'ADMIN', 
created_date, --CURRENT_TIMESTAMP,
modified_by, --'ADMIN', 
modified_date --CURRENT_TIMESTAMP
)
VALUES
(
'REQUEST',
'assets/',
'ID',
null,
'FULL',
null,
null,
'COINCAP API 2.0',
'COINCAP',
'COINCAP',
'COINCAP-DATA-HUB',
'COINCAP_DATA',
'ASSETS',
'PARQUET',
null,
null,
null,
null,
'gzip',
true,
true,
'dev-coincap-data',
'input/coincap_assets/',
'archive/coincap_assets/',
'ADMIN',
CURRENT_TIMESTAMP,
'ADMIN',
CURRENT_TIMESTAMP
);

DELETE FROM metadata_utilities.ingestion_column_details WHERE table_name = 'ASSETS';
INSERT INTO metadata_utilities.ingestion_column_details (column_name,datatype,ordinal_position,mapping_column, project_id, database_schema,table_name,modified_by,modified_date,created_by,created_date) VALUES 
('ID','STRING',1,'ID','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('RANK','INT64',2,'RANK','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('NAME','STRING',3,'NAME','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('SUPPLY','FLOAT64',4,'SUPPLY','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('MAXSUPPLY','FLOAT64',5,'MAXSUPPLY','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('VOLUMEUSD24HR','FLOAT64',6,'VOLUME_USD_24HR','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('PRICEUSD','FLOAT64',7,'PRICE_USD','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('CHANGEPERCENT24HR','FLOAT64',8,'CHANGE_PERCENT_24HR','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('VWAP24HR','FLOAT64',9,'VWAP_24_HR','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('EXPLORER','FLOAT64',10,'EXPLORER','COINCAP-DATA-HUB', 'COINCAP_DATA','ASSETS','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP);