DELETE FROM metadata_utilities.ingestion_config WHERE table_name = 'SOLANA_HISTORY';
INSERT INTO metadata_utilities.ingestion_config
(
ingestion_type, --TEST,
source_schema_table_name, --PREFIX_PATH_FILE_NAME, 
primary_key_column, --NULL, 
incremental_date_column, --NULL,
load_type, --FULL,  
extra_parameters, --NULL, 
partitioned_by, --NULL,
api_source_name, --TEST,    
source_system, --GCS,
connection_name, --TEST,
project_id, --TEST,
database_schema, --TEST, 
table_name, --TEST_TABLE,
file_format, --CSV, 
header, --NULL,
delimiter, --',',
quote_characters, --'"',
escape_characters, --NULL,
accepted_encoding, --gzip,
is_parquet, --false,
to_parquet, --true,
bucket, --dev-test-data,
bucket_destination, --input/,
archive_destination, --archive/test/,
created_by, --'ADMIN', 
created_date, --CURRENT_TIMESTAMP,
modified_by, --'ADMIN', 
modified_date --CURRENT_TIMESTAMP
)
VALUES
(
'REQUEST',
'assets/solana/history/',
'TIME',
'TIME',
'INCR',
'h1',
null,
'COINCAP API 2.0',
'COINCAP',
'COINCAP',
'COINCAP-DATA-HUB',
'COINCAP_DATA',
'SOLANA_HISTORY',
'PARQUET',
null,
null,
null,
null,
'gzip',
true,
true,
'dev-coincap-data',
'input/coincap_solana_history/',
'archive/coincap_solana_history/',
'ADMIN',
CURRENT_TIMESTAMP,
'ADMIN',
CURRENT_TIMESTAMP
);

DELETE FROM metadata_utilities.ingestion_column_details WHERE table_name = 'SOLANA_HISTORY';
INSERT INTO metadata_utilities.ingestion_column_details (column_name,datatype,ordinal_position,mapping_column, project_id, database_schema,table_name,modified_by,modified_date,created_by,created_date) VALUES 
('TIME','INT64',1,'TIME','COINCAP-DATA-HUB', 'COINCAP_DATA','SOLANA_HISTORY','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('DATE','STRING',2,'DATE','COINCAP-DATA-HUB', 'COINCAP_DATA','SOLANA_HISTORY','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('PRICEUSD','FLOAT64',3,'PRICE_USD','COINCAP-DATA-HUB', 'COINCAP_DATA','SOLANA_HISTORY','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP),
('CIRCULATINGSUPPLY','FLOAT64',4,'CIRCULATING_SUPPLY','COINCAP-DATA-HUB', 'COINCAP_DATA','SOLANA_HISTORY','ADMIN',CURRENT_TIMESTAMP,'ADMIN',CURRENT_TIMESTAMP);