DELETE FROM metadata_utilities.spark_config WHERE table_name = 'BitcoinHistoryLinearRegression';
INSERT INTO metadata_utilities.spark_config
(
application_name,
executor_instances,
executor_memory,
executor_cores,
driver_memory,
driver_cores,
auto_broadcast_join_threshold,
shuffle_partitions,
broadcast_timeout,
connection_id,
connection_name,
bucket,
source_file,
created_by,
created_date,
modified_by,
modified_date
)
VALUES
(
'BitcoinHistoryLinearRegression',
'4',
'4g',
'4',
'4g',
'2',
'-1',
'200',
'1200',
7,
'GCS_COINCAP',
'dev-coincap-data',
'spark/bitcoin_history_linear_regression.py',
'ADMIN',
CURRENT_TIMESTAMP,
'ADMIN',
CURRENT_TIMESTAMP
);

