DROP TABLE IF EXISTS metadata_utilities.ingestion_config;
CREATE TABLE IF NOT EXISTS metadata_utilities.ingestion_config (
ingestion_config_id SERIAL PRIMARY KEY,
ingestion_type VARCHAR(255) NOT NULL,
source_schema_table_name VARCHAR(255) NOT NULL, 
primary_key_column VARCHAR(255), 
incremental_date_column VARCHAR(255),
load_type VARCHAR(50) NOT NULL,  
extra_parameters VARCHAR(255), 
partitioned_by VARCHAR(255),
api_source_name VARCHAR(255),    
source_system VARCHAR(255) NOT NULL,
connection_name VARCHAR(255) NOT NULL,
project_id VARCHAR(255) NOT NULL,  
database_schema VARCHAR(255) NOT NULL, 
table_name VARCHAR(255) NOT NULL,
file_format VARCHAR(50), 
header VARCHAR(255),
delimiter VARCHAR(50),
quote_characters VARCHAR(50),
escape_characters VARCHAR(50),
accepted_encoding VARCHAR(50),
is_parquet  BOOLEAN,
to_parquet BOOLEAN NOT NULL,
bucket VARCHAR(255) NOT NULL,
bucket_destination VARCHAR(255) NOT NULL,
archive_destination VARCHAR(255) NOT NULL,
created_by VARCHAR(255) NOT NULL, 
created_date TIMESTAMP NOT NULL,
modified_by VARCHAR(255) NOT NULL, 
modified_date TIMESTAMP NOT NULL
);